formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  LederWorks Azure Easy Alerting Terraform Module

  {{ .Header }}

  ## Examples

  ```hcl
  {{ include "examples/example.tf" }}
  ```

  {{ .Providers }}

  This module never been tested below terraform 1.0.0 and azurerm 2.76.0, suggesting to use latest versions. 

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: false
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true